### ISSUE TITLE
GPG keyserver not working

### ISSUE THREAD

**Issue by rohin-dasari** [sylabs/singularity-userdocs#108]
## Which Document page:

On what page is the problem?
Ob the installation section of the user-guide. The exact issue is in the `install the debian ubuntu package using apt`
https://docs.sylabs.io/guides/3.3/user-guide/installation.html#install-the-debian-ubuntu-package-using-apt

### Expected results:

What are you expecting to see?
The command to enable the NeuroDebian repository with the gpg key information provided should run without failure.
Here is the command copied from the docs:
```
$ sudo wget -O- http://neuro.debian.net/lists/xenial.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list && \
    sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 && \
    sudo apt-get update
```

### Actual results:

What is the problem, what's misspelled, or what's missing?
When I run the command I get this error: 

```
Executing: /tmp/apt-key-gpghome.3OvrUgQWhe/gpg.1.sh --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
gpg: keyserver receive failed: Server indicated a failure
```
After doing some research, it looks like the SKS keyservers are deprecated.

I was able to workaround this error by substituting a different keyserver. I used `pgp.mit.edu`, but I also confirmed that `hkp://keyserver.ubuntu.com:80` works as well. 

The docs should likely be updated with a new keyserver, otherwise the apt installations will not work.

**Comment by dtrudg** [comment]
Hello,

You are looking at documentation for version 3.3 of Singularity, which is very outdated. Note the 3.3 in the URL:

https://docs.sylabs.io/guides/3.3/user-guide/installation.html#install-the-debian-ubuntu-package-using-apt

The documentation for the latest version (3.10 at present) can always be found via a URL that has 'latest' in place of the specific version:

http://sylabs.io/guides/latest/user-guide
http://sylabs.io/guides/latest/admin-guide

We no longer give instructions for installing from neurodebian packages, as it does not track SingularityCE versions, so there is nothing to update. The documentation for old versions (3.3 in your case) remains online for reference, but is not updated.
