### ISSUE TITLE
Addition of extra dependencies to the sif file

### ISSUE THREAD

**Issue by ajbanegas** [sylabs/singularity-userdocs#110]
## Which Document page:

On what page is the problem?
https://docs.sylabs.io/guides/3.5/user-guide/gpu.html

### Expected results:

What are you expecting to see?
Is the definition file for TF image is available?

### Actual results:

What is the problem, what's misspelled, or what's missing?
I need to extend the TF image with more dependencies, so I should be able to modify it or rebuild it from the definition file.

**Comment by dtrudg** [comment]
The example is pulling a Docker Hub image:

```
singularity pull docker://tensorflow/tensorflow:latest-gpu
```

This means there is no Singularity definition file. However, you can extend it by writing a definition file that starts from the docker image:

```
Bootstrap: docker
From: tensorflow/tensorflow:latest-gpu

%post
# My additions here
```

I don't really think this is an issue with the documentation, as this is covered in the build section, e.g.:

https://docs.sylabs.io/guides/latest/user-guide/build_a_container.html#building-containers-from-singularityce-definition-files
