### ISSUE TITLE
missing ce in command when pulling

### ISSUE THREAD

**Issue by skr3178** [sylabs/singularity-userdocs#121]
Corrected version of the command ¨--ce¨ added
```
export VERSION=3.10.4 && # adjust this as necessary \
    mkdir -p $GOPATH/src/github.com/sylabs && \
    cd $GOPATH/src/github.com/sylabs && \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd ./singularity && \
    ./mconfig
```

Old incorrect version of command:
`https://github.com/sylabs/singularity/releases/download/v3.10.4/singularity-3.10.4.tar.gz`

**Comment by dtrudg** [comment]
Hello. Thanks for reporting this. Could you provide a link to the page with the incorrect information?

Thanks!

**Comment by dtrudg** [comment]
I haven't been able to find this in a grep. Closing.

Please feel to re-open if the error exists in a current version of the documentation, with a pointer to where exactly it is. Thanks!
