### ISSUE TITLE
Instructions to uninstall and/or upgrade in user guide

### ISSUE THREAD

**Issue by Lauler** [sylabs/singularity-userdocs#124]
The user guide lacks instructions on how to uninstall and remove singularity from a system. User guide docs also lacks explicit instructions on best practices to upgrade singularity to a newer version. Do I remove the older version first? Do I install the new one on top of the old one? The admin guide says:

> If you have an earlier version of SingularityCE installed, you should [remove it](https://docs.sylabs.io/guides/3.10/admin-guide/installation.html#remove-an-old-version) before executing the installation commands.

These instructions should, if applicable, also be in the user guide.

**Comment by dtrudg** [comment]
The user guide isn't really intended to cover installation / removal / upgrade, as that's why we have the admin guide. We have, at times, though about removing all installation instructions form the user guide. The quick start was left as a compromise.

We do, in multiple locations, refer to the admin guide...

> For a detailed guide to installation and configuration, please see the separate Admin Guide

We can add explicit links that mention removal / upgrade, but I don't think we'll duplicate more content between the guides.

**Comment by Lauler** [comment]
I'd suggest perhaps strategically adding the word(s) "uninstallation" somewhere in that sentence or paragraph that points towards the Admin Guide, because people like myself tend to skim docs quickly and/or ctrl+f the terms "uninstall", "remove", "upgrade". I tried both ctrl+f and tried using the search feature in the user guide docs, neither led me to find that tucked-away sentence referring pointing to the Admin Guide. 

It is not immediately obvious to all external users, like myself, what the distinction between Admin Guide and User Guide is. To my beginner eyes, the wording Admin Guide gives me the impression that it might as well be something specific to system administrators of HPC systems and not at all relevant to me as merely a user of these systems. 

In any case. No need to have full install/uninstall instructions in the user guide. But I think specifically using the words "uninstall" or "remove" in close vicinity to the location where you're pointing users towards Admin Guide would be very helpful to users.
