### ISSUE TITLE
Clarify how to pass variables from host environment to build environment

### ISSUE THREAD

**Issue by myoung3** [sylabs/singularity-userdocs#15]
Neither the definition file nor the `singularity build` help file explicitly state that the build environment doesn't inherit host environment variables.
https://sylabs.io/guides/3.8/user-guide/cli/singularity_build.html
https://sylabs.io/guides/3.8/user-guide/definition_files.html

This is a reasonable approach to building (it keeps the build environment from being polluted by the state of the host), but it would be nice if it were spelled out explicitly in both of these files. 

Additionally, it would be good to document how to pass a variable if you actually need to do this. Here's a [use case](https://github.com/cli/cli/issues/2680#issuecomment-895339304): passing a token into the build environment to authenticate before downloading something. I tried but could not figure out how to accomplish passing a variable without actually just writing it to file.

**Comment by dtrudg** [comment]
Will add a note on the clean environment, and pointing to new templating functionality for passing things into a build.

**Comment by preminger** [comment]
On passing build-time values into a build file, see the now-completed #199 

(Note that this functionality is available on the `main` branch of https://github.com/sylabs/singularity, as well as on any release whose version number starts with "4", but not on older versions.)
