### ISSUE TITLE
Document --device and --cdi-dirs functionality in User Guide

### ISSUE THREAD

**Issue by preminger** [sylabs/singularity-userdocs#165]
**Type of issue**
Addition to documentation

**Description of issue**
Once the status of OCI functionality is no longer "experimental", the User Guide should be amended to reflect this functionality, and that will need to include documentation of our support for CDI device mapping (specifically: `--device` and `--cdi-dirs` flags). See sylabs/singularity#1394 and https://github.com/sylabs/singularity/pull/1459

**Comment by dtrudg** [comment]
This issue should be opened against the userdocs repo - https://github.com/sylabs/singularity-userdocs/issues

**Comment by preminger** [comment]
Whoops, sorry about that! I hope "transfer issue" was the right thing to do in this case (as opposed to closing the issue & reopening it here).

**Comment by preminger** [comment]
Subsumed under #170
