### ISSUE TITLE
--cpus option units

### ISSUE THREAD

**Issue by dmd** [sylabs/singularity-userdocs#211]
According to https://docs.sylabs.io/guides/main/user-guide/cgroups.html : 

>>>
`--cpus` sets the number of CPUs, or fractional CPUs, that the container can use. The minimum is `0.01` or one tenth of a physical CPU. The maximum is the number of CPU cores on your system.
>>>

What are the units here? `0.01` seems to me like it's one **hundredth** of a physical CPU, not one tenth.

**Comment by dtrudg** [comment]
Thanks, we'll fix this. Hundredths is correct. The unit is a CPU (16 on this machine and the code knows the correct valid range if you try e.g. `0.009`).

```
05:59 pm $ singularity run --cpus 0.01 docker://alpine
INFO:    Using cached SIF image
Singularity> ^C

Singularity> 
dtrudg-sylabs@mini:~/Git_Sylabs/singularity
06:00 pm $ singularity run --cpus 0.009 docker://alpine
INFO:    Using cached SIF image
FATAL:   cpus value must be in range 0.01 - 16
```
