### ISSUE TITLE
The Instructions on Installation Singularity on MacOS is not working

### ISSUE THREAD

**Issue by santataRU** [sylabs/singularity-userdocs#254]
I attempted to install Singularity on MacOS with an M3 chip using the instructions provided on the webpage, but it did not work. 

https://docs.sylabs.io/guides/3.0/user-guide/installation.html#install-on-windows-or-mac

Error messages: 
(baltica) xiaolei@ baltica % **brew install --cask virtualbox && \
brew install --cask vagrant && \
brew install --cask vagrant-manager**

==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################################################# 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/fb0107509ac6f54572b501ed73abed468be328f6/Casks/v/virtualbox.rb
################################################################################################################################################################# 100.0%
==> Downloading https://download.virtualbox.org/virtualbox/7.1.4/VirtualBox-7.1.4-165100-macOSArm64.dmg
################################################################################################################################################################# 100.0%
==> Installing Cask virtualbox
==> Running installer for virtualbox with sudo; the password may be necessary.
Password:
installer: Package name is Oracle VirtualBox
installer: choices changes file '/private/tmp/choices20241122-52078-jzo0ym.xml' applied
installer: Installing at base path /
installer: The install was successful.
🍺  virtualbox was successfully installed!
==> Downloading https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_darwin_arm64.dmg
################################################################################################################################################################# 100.0%
==> Installing Cask vagrant
==> Running installer for vagrant with sudo; the password may be necessary.
Password:
installer: Package name is Vagrant
installer: Installing at base path /
installer: The install was successful.
🍺  vagrant was successfully installed!
==> Caveats
vagrant-manager is built for Intel macOS and so requires Rosetta 2 to be installed.
You can install Rosetta 2 with:
  softwareupdate --install-rosetta --agree-to-license
Note that it is very difficult to remove Rosetta 2 once it is installed.

==> Downloading https://github.com/lanayotech/vagrant-manager/releases/download/2.7.1/vagrant-manager-2.7.1.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/18744882/9d66a480-17c4-11ea-8f71-947b3a37db21?X-Amz-Algorithm=AWS4-HMA
################################################################################################################################################################# 100.0%
==> Installing Cask vagrant-manager
==> Moving App 'Vagrant Manager.app' to '/Applications/Vagrant Manager.app'
🍺  vagrant-manager was successfully installed!
(baltica) xiaolei@ baltica % pwd
/Users/xiaolei/miniforge3/envs/baltica/baltica/baltica
(baltica) xiaolei@ baltica % **mkdir vm-singularity && \
    cd vm-singularity**
(baltica) xiaolei@ vm-singularity % ls
(baltica) xiaolei@ vm-singularity % pwd
/Users/xiaolei/miniforge3/envs/baltica/baltica/baltica/vm-singularity
(baltica) xiaolei@ vm-singularity % **export VM=sylabs/singularity-3.0-ubuntu-bionic64 && \
    vagrant init $VM && \
    vagrant up && \
    vagrant ssh**
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'sylabs/singularity-3.0-ubuntu-bionic64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'sylabs/singularity-3.0-ubuntu-bionic64'
    default: URL: https://vagrantcloud.com/api/v2/vagrant/sylabs/singularity-3.0-ubuntu-bionic64
==> default: Adding box 'sylabs/singularity-3.0-ubuntu-bionic64' (v20190925.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/sylabs/boxes/singularity-3.0-ubuntu-bionic64/versions/20190925.0.0/providers/virtualbox/unknown/vagrant.box
==> default: Successfully added box 'sylabs/singularity-3.0-ubuntu-bionic64' (v20190925.0.0) for 'virtualbox'!
==> default: Importing base box 'sylabs/singularity-3.0-ubuntu-bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'sylabs/singularity-3.0-ubuntu-bionic64' version '20190925.0.0' is up to date...
==> default: Setting the name of the VM: vm-singularity_default_1732280463662_90434
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "0ddfcbb4-f876-444f-80e7-7c519d394578", "--type", "headless"]

Stderr: VBoxManage: error: The VM session was aborted
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface ISession

**Comment by dtrudg** [comment]
You have linked to the instructions for Singularity version 3.0, which are outdated. Please follow the instructions for the latest version, via...

https://sylabs.io/docs/

Which will take you, eventually, to:

https://docs.sylabs.io/guides/latest/admin-guide/installation.html#mac
