### ISSUE TITLE
how to remove an account?

### ISSUE THREAD

**Issue by thibaulttabarin** [sylabs/singularity-userdocs#78]
## Which Document page:

On what page is the problem?
main page 
https://cloud.sylabs.io/dashboard#

### Expected results:

What are you expecting to see?
Somewhere I can delete my account

### Actual results:

What is the problem, what's misspelled, or what's missing?
I have created several account and I want to remove the empty one. It seems simple but I haven't any information so far. Could you help me?

**Comment by dtrudg** [comment]
Please contact support@sylabs.io for issues related to the cloud.sylabs.io services. Thank you.
